// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrRtTvNMAVdgg0He5YBeXX0OcsEcpd484',
    appId: '1:701118034049:android:05a056f20a8a98e6349d80',
    messagingSenderId: '701118034049',
    projectId: 'shadowtask-b5b35',
    databaseURL: 'https://shadowtask-b5b35-default-rtdb.firebaseio.com',
    storageBucket: 'shadowtask-b5b35.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZYs9WqvOPMh-hWr3yjoFSeM8HYAh9ilY',
    appId: '1:701118034049:ios:5309b74fa5018ba7349d80',
    messagingSenderId: '701118034049',
    projectId: 'shadowtask-b5b35',
    databaseURL: 'https://shadowtask-b5b35-default-rtdb.firebaseio.com',
    storageBucket: 'shadowtask-b5b35.appspot.com',
    iosClientId:
        '701118034049-747c0r4bgbeftf45smts72udq3adn9nj.apps.googleusercontent.com',
    iosBundleId: 'com.theshadowtech.shadowtask',
  );
}
